vim.lsp.enable('gopls')
vim.lsp.enable('rust_analyzer')
vim.lsp.enable('pyright')
vim.lsp.enable('tsserver')
vim.lsp.enable('clangd')
vim.lsp.enable('html')
vim.lsp.enable('cssls')
vim.lsp.enable('jsonls')
vim.lsp.enable('bashls')
vim.lsp.enable('yamlls')
vim.lsp.enable('dockerls')
vim.lsp.enable('graphql')
vim.lsp.enable('lua_ls')

